//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class klijenti
    {
        public int Id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string adresa { get; set; }
        public string oib { get; set; }
        public string broj_mobitela { get; set; }
    }
}
